### ISSUE TITLE
Can you offer pretrained weights and char-set?

### ISSUE THREAD

**Issue by GodOfSmallThings** [FangShancheng/conv-ensemble-str#1]
I want to evaluate this model, but there is no weights to test.
If weights and char-set can be offered, it would be very grateful. Thank you.

**Comment by FangShancheng** [comment]
@GodOfSmallThings Hi,
We will retrain a model based on the released code as soon as possible, and then release it together with charset and tfrecord tools. Thank you for concerning.

**Comment by FangShancheng** [comment]
@GodOfSmallThings a pretrained model can be found [here](https://www.dropbox.com/s/81j7zcr23vqd8zq/model.ckpt.tar.gz?dl=0).
